--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: search
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO search;

--
-- Name: label; Type: TABLE; Schema: public; Owner: search
--

CREATE TABLE public.label (
    id integer NOT NULL,
    name character varying(20) NOT NULL
);


ALTER TABLE public.label OWNER TO search;

--
-- Name: label_id_seq; Type: SEQUENCE; Schema: public; Owner: search
--

ALTER TABLE public.label ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.label_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: search
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO search;

--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: search
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: search_result; Type: TABLE; Schema: public; Owner: search
--

CREATE TABLE public.search_result (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    link character varying(1000) NOT NULL,
    snippet text,
    type smallint NOT NULL
);


ALTER TABLE public.search_result OWNER TO search;

--
-- Name: search_result_id_seq; Type: SEQUENCE; Schema: public; Owner: search
--

ALTER TABLE public.search_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.search_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: search_result_label; Type: TABLE; Schema: public; Owner: search
--

CREATE TABLE public.search_result_label (
    search_result_id integer NOT NULL,
    label_id integer NOT NULL
);


ALTER TABLE public.search_result_label OWNER TO search;

--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: search
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20251127095935	2025-11-27 09:59:39	32
DoctrineMigrations\\Version20251127104714	2025-11-27 10:47:25	2
DoctrineMigrations\\Version20251127105505	2025-11-27 10:55:11	9
DoctrineMigrations\\Version20251127105833	2025-11-27 10:58:48	18
DoctrineMigrations\\Version20251128025842	2025-11-28 02:58:45	3
DoctrineMigrations\\Version20251128031052	2025-11-28 03:11:00	2
\.


--
-- Data for Name: label; Type: TABLE DATA; Schema: public; Owner: search
--

COPY public.label (id, name) FROM stdin;
1	常规网页
2	公众号
\.


--
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: search
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- Data for Name: search_result; Type: TABLE DATA; Schema: public; Owner: search
--

COPY public.search_result (id, title, link, snippet, type) FROM stdin;
103	竹溪“国芯一号”一周年:看县域“算力革命”交出了怎样的答卷?	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BXXCYo8D49HaEYkFP8aUe2FqXa8Fplpd90kwy36cAoKzAXxkeJUiCxaJab9Lp_K3drfeA_6MYHMb6oyeHmIVzY5sIpDmXfQoVzMTtsw8LthFjneMHidBNzOIJ_pH1hFDyC2L9ntqbUxOwUAmk5F9U63lHFWb7p1EnXhjmbHiX17t03ceXc1oGCc6GEXNRnYeGcmCxXzlFrFZe0WC6Sbi7DA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE3491ED85D652F9FFBE641EF9AADAFA95A38569291149		1
104	国芯云一号“互联网+”行动计划正式启动	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6ft3wfAVofsP5Peu-UiA4DKzRL4-IAsVKdg6F58J21HOVgrFeYQugDtFZY-dfomvx_tw_8wWX9wnplDUSfiM7LrPF-Tf04vghOfppgj6ZcunyC-YhWOBEylxfWEvd31cYIVbVSFMH2u--y2ru_OpFklzOJBX7BXPy5wniKrYMYJBXO2IYbEIMRGgRxCb16YI3g7-iRkh-MFO2nJla1_umqG4wyML7V7DPAJ4H5TyEWTJ2NWhsift3FqShwEYkA6yMuurjcjrbp6Q.&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE3491ED85D652F9FFBE641EF9AADAFA95A38569291149		1
105	竹溪数字经济产业链招商暨2025“国芯一号”生态合作伙伴大会圆满举办!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BXXCYo8D49HaEYkFP8aUe2FqXa8Fplpd9_5Vb1bFTo43aqJ-Al51qbl_Yq59YH0tqIvzzFgNO2BuuQQ2uR9ycp7MVgKOwGRxP_iBaCbnbCiWULrSD1Rs5xRi_JPCT5H77EOQzpZ_0GTRl6bXx89GLZCH5pXQb-9pFVCVmj4_sRmzH1FPoKJHpSZBEhjW1x-E2PeWKhXzgH4xFkDr8IT4KYw..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE3491ED85D652F9FFBE641EF9AADAFA95A38569291149		1
106	竹溪数字经济产业链招商暨“国芯一号”生态合作伙伴大会举行	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BXXCYo8D49HaEYkFP8aUe2FqXa8Fplpd9GU1w92hZkWoJTcpYNZYPGQb5ZNtUre3EI2eYk4uJ5QHmp9T6bRvezCabbNxWg-xGzU0ItkU1ym4Aob0QsUj3Nb-qBQDaCAf9IskEtuDYEdi4lfI_qn2cxUKbkid-m4Qb4gxYBC0OXbMxTuAdU1s26t9Guf8QCy2xxZo8xIpPnJKFW6cwuUnkdA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE3491ED85D652F9FFBE641EF9AADAFA95A38569291149		1
107	许庆一师文明与来溪参加数字经济产业链招商暨2025“国芯一号”生态合作伙伴大会的企业家代表座谈	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BXXCYo8D49HaEYkFP8aUe2FqXa8Fplpd9GU1w92hZkWoJTcpYNZYPGQb5ZNtUre3EI2eYk4uJ5QHmp9T6bRvezCDQcH9iXmd5zpgbOxIiLJpzJaGYMydQnPGwNfyljUEy2GA2j0AqdU51l6c5NSdTV697IMkXYN_df_c4WDoed8OPF0XbvEwrYU_9P7W13YGFE1H6V3_eRfECYioxHkzTmA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE3491ED85D652F9FFBE641EF9AADAFA95A38569291149		1
108	转发拿电脑!来自“国芯云一号”的星际战舰登陆珠海,掀起云计算的滔天大浪	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6ft3wfAVofsP5Peu-UiA4DKzRL4-IAsVKdg6F58J21HOVgrFeYQugDtFZY-dfomvx_tw_8wWX9wnplDUSfiM7LrPF-Tf04vghOfppgj6ZcumR4TnC87WEffH9LjcxlE633FgoZCdIV78Qt7oTLn8JZ2AwvF1vfABExVzM_EVWMiFK1mTsfGVLC4pbkDEx5hzQ3J6eKi79Vvb8HjLnYbApDckxJ9cmYTPABVnXvuws3_YSLYZpNW8rBwPpuFXsjBJYpSN3Vg2WPFmxqRhH1RHRqINjVnq40nhSiZqwg0yoRFw.&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE3491ED85D652F9FFBE641EF9AADAFA95A38569291149		1
109	肩负重大使命,追赶顶级水平,拥抱伟大国芯!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BXXCYo8D49HaEYkFP8aUe2FqXa8Fplpd9lsSzcVU-nMGD7gtnn-sinjAuDycdMnsoiLw4wAlMNDRPtgS61B5yR8chW34y1UbDLInhAbH95LWttP8ziE3CRcInmkOpOQMq8QRTfiENvA6_P252S2Y7XsUqR-JU7JGPrr4FiPCZVLoKpYofRvcbIsPw-wIW9jOZHaMx8odxBO3m0CtGSSkZQQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE3491ED85D652F9FFBE641EF9AADAFA95A38569291149		1
110	北方有佳人绝世而独立一顾倾人城再顾倾人国,宁不知倾城与倾国?佳人难再得--士兰微 紫光国芯!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BXXCYo8D49HaEYkFP8aUe2FqXa8Fplpd9odw_bwq1ffWJmSm_y5fls66YGlIQp8vIqIGir0q1qMLQ_ykmOAISFfUIHVSN2yd5Ugq4nyYh0nqNfXCjiUkz1RtnstEpBdfwhwU-u_cau8JTHFd3UFEPipjAjpJVoGHcLC1hLw-VHlS6Ot2-dovY3TCf9JmSS7doc7ccxmB2re9QL0Hr9Gyd3Q..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE3491ED85D652F9FFBE641EF9AADAFA95A38569291149		1
111	一幅K线图究竟内在隐藏有何等深奥密码相信很多人一定是匪夷所思百思不得其解--002049紫光国芯 用友网络 士兰微	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BXXCYo8D49HaEYkFP8aUe2FqXa8Fplpd9odw_bwq1ffWJmSm_y5fls66YGlIQp8vIqIGir0q1qMLQ_ykmOAISFV3OncRnI1jdobgwkEq5W1-PZkYIdi3EzP2SdT-0hy8r_sall76-2U1uvJtJBA5QsJXG-FfR3PBhyLgWldSgWn-RftgTL6I3H_Tp8H56XyDNaYhXPnzaApqE8RsmObDbtQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE3491ED85D652F9FFBE641EF9AADAFA95A38569291149		1
112	错过“紫光国芯”,又一军工龙头业绩暴增817%,12月远超京东方A!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BXXCYo8D49HaEYkFP8aUe2FqXa8Fplpd9OptUSK0aaXjHwoqoebvHdvHWknJsk1W4mpFWuAcfiadrQf2XZ-QC2-BQbynXnp4o3QpGM3r7bVkISrtgnY4zk5aclYa1QVf3JZ4ObLHkGMlUTHixn2Ehdi6PcnSz7vIpuRsheUy-JMYunLEMAiexZnCtc9Dk4zYdOgDxH4IqkC-54z_tGSZTqA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE3491ED85D652F9FFBE641EF9AADAFA95A38569291149		1
113	1月6日抱富指南:益客食品发行,国芯科技上市......	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Be4yTvCLfkmCEYkFP8aUe2FqXa8Fplpd91AQXjLcK-_AQjbt2Gql1BQzdmRWJL_kJp1cJ5XDXOPxo692F6KxUlGq58BBEZDfxbN4JcZWF7rr3Jz-PfQJZSVrVMIpI8FsOPH6cahYhOVc_1E4Sip-VERa2yM6Qqm_4-BKXujLL6sL2VPaiFQwRoDyTcgMO1wr0U_WIwv2eM9fP28temKTOwg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE43AF167C2DAA0106459FE52BF53101DBBBE16929114B		1
114	同学加油丨2023紫光国芯高考统一试卷(全国卷)	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Be4yTvCLfkmCEYkFP8aUe2FqXa8Fplpd9z7dI13lgMGwATS6oh2-IdScZI70icpb9Sbi2top1aT_Tg21sdTCxEBxFpCdiygN2XOh79QHZHRggLym_iQntcT986J0YVKKNueuFSHvWq42HgDm0nlFhvSuVHMjxmDmY61W39i6E0DjoMSWbYsEHKSP6jei6qDul5k50BcnMtNlS6t2rFt2rnA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE43AF167C2DAA0106459FE52BF53101DBBBE16929114B		1
115	不止谈硬件:你该不该买紫光国芯?	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Be4yTvCLfkmCEYkFP8aUe2FqXa8Fplpd9X-sL87OlpDRmaefOiLfOd-Ye1Iy77DGVvDyUIfMLXt_C6AOr0EbmcZeSLzw2-CjYPikkKESZAXTWDQpl501aRZyTPim7OkuvVY8C8jDXmSu24L7tLF1XPcs1FDJzIaBpJ8KNPNA4wVsPLkvcDCDqCYhwEjTo-UUvrXmfn0NpeiT0OK9DLfgmPA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE43AF167C2DAA0106459FE52BF53101DBBBE16929114B		1
116	杭州国芯参加2020(秋季)亚洲蓝牙耳机展,展位号F06!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Be4yTvCLfkmCEYkFP8aUe2FqXa8Fplpd9fXe9BHKlH6X2JgmT4qOxzKdsLp9V24lPwrv4JNDGUjW2ICvfRz3sSmwcPGETWItvogh675F8SXUsGRonlpKTcxx5Rl1leCxw2on_LkFzpQsGPQn9EKWaSn8KBQmolVkZMwiwdBEKpSx6Gp3Ctzx_i5HFULYWL5ejihP9a16xIRiq3X8EKMKOIA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE43AF167C2DAA0106459FE52BF53101DBBBE16929114B		1
117	@6月上海见!杭州国芯助力TWS成为下一个语音入口	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Be4yTvCLfkmCEYkFP8aUe2FqXa8Fplpd9fXe9BHKlH6X2JgmT4qOxzKdsLp9V24lPwrv4JNDGUjW2ICvfRz3sStYEvchZabmVOw3bWEuBzFcCNoTcv1gIhhik9eDkj50xRwADyrQVkkBfogqAhksD6UvQIZHoEd-M-vs7WxiOFA7xbpQ8mvWRRwHJqdHE58EAr0Ngyn69qLk5eBgmN3LoYQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE43AF167C2DAA0106459FE52BF53101DBBBE16929114B		1
118	名企行 | 丁香1号书院师生走进西安紫光国芯半导体有限公司研学交流	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Be4yTvCLfkmCEYkFP8aUe2FqXa8Fplpd9Yb1FXySx_haKEN9NuyD6BoHjVmSiOLkmndVpA9uQiMwO3TrXRlDa2UxKaV2n3VHWWjAa6yPY4mKPnte82CUQ9YozgSIWQjLxIdQ3pTIyuWUiuxFuPudER9Xb9rDchyPWgm8ycuN-hemTc6GTl9hwTVuz5JWR3Y1lUbn6IQLwkvK54z_tGSZTqA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE43AF167C2DAA0106459FE52BF53101DBBBE16929114B		1
119	喜讯:国芯云一号获奖首届珠海市香洲区科技创新大赛	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6ft3wfAVofsP5Peu-UiA4DKzRL4-IAsVKo6CgsrBpePeVgrFeYQugDtFZY-dfomvx_tw_8wWX9wnplDUSfiM7LrPF-Tf04vghOfppgj6ZcumR4TnC87WEfd0Rz9uEhVI_dLjYQ-wsBvMgz2m8AKt4MNVJKOi84cbvJ-66h6blioxK_nyxJ-kfZ7bQFYes9IzZVXhGygfENEbdriPmrwpKZVZhVyCAzGiEIsaPqcaO1rEpm5cbk79qBUWeBwEfNpGWZvnoPUBSsr8.&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE43AF167C2DAA0106459FE52BF53101DBBBE16929114B		1
120	牢牢跟着国家队死死抱住姊妹花永远不忘拥有一颗中国芯!--000938紫光股份 002049紫光国芯!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Be4yTvCLfkmCEYkFP8aUe2FqXa8Fplpd9odw_bwq1ffWJmSm_y5fls66YGlIQp8vIqIGir0q1qMLQ_ykmOAISFVcOseld8GsJhmvMEJhXasI8f1RCzuTY_JtXqHUMosHuv9RkQMFZdwx5p8m-euCw8Pm4B3ps7NJbo-EOczWEg19zS6ycRrDlycX5ZVQNioJzSglxEGevnWxflztgI7RZ1g..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE43AF167C2DAA0106459FE52BF53101DBBBE16929114B		1
121	国芯在2020(冬季)亚洲蓝牙耳展,展位号:F06!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Be4yTvCLfkmCEYkFP8aUe2FqXa8Fplpd9fXe9BHKlH6X2JgmT4qOxzKdsLp9V24lPwrv4JNDGUjW2ICvfRz3sSpjUOOhntHsREZnPF54l9xRNU9TAMRkFmbvnlivbx6bt09Dmav_NSsNpDvVP7J3PS_zSKbRsIT7mv33t5Q8jXdM2ER6PQVIM_Es5qQ8IxZgslM1YWGrYF3FQ_LeJW-Rhtg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE43AF167C2DAA0106459FE52BF53101DBBBE16929114B		1
122	员工爆国芯科技强制研发加班至10点,一周多干出三工作日……	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Be4yTvCLfkmCEYkFP8aUe2FqXa8Fplpd9lcS3EJoYm05UcKreU5G3k0sQQ95d6I1ta0Wpbp1vgiYfQ5LhJcaRN5PGtCkd1bC_sqNzk5FJqjGAvfnPCKkl6BZWazWU5MoYCWuEXC4mTyBUFvMTqtGCs8Immn-T1kyr5UeuvB8x4K_yuxaH1ZJ-lOuJsEjwXdeq5IYFxEFSgILS-e4Yz84xMA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE43AF167C2DAA0106459FE52BF53101DBBBE16929114B		1
123	再见,棠湖西路二段8号!你好,国芯大道388号!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BJjTi0-oOltiEYkFP8aUe2FqXa8Fplpd95b3fi0vCD8I8UBd1MZxra3SQgm6MiWGRZWdmlovLqfbFm-jPy2X_cJViyjDLSgULTGuFD2SD9qsh3iqtSKuIke2sjrvuNvsaTU6EpOkWySobkYvuPRYKcvQhk4QJdoeBo2L7iyTewA4wXv5stW2H97JBN5LhyvnHdS_Zw95-6pjy08OLTBhW0A..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE519EE982D156FEFBBA6019A5366EFE18CBCD6929114E		1
124	【进口】我国前7个月集成电路进口减少16.8%;西安紫光国芯被陕西发改委通报;宏芯气体/派恩杰半导体/华封科技等获新一轮融资	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BJjTi0-oOltiEYkFP8aUe2FqXa8Fplpd9DgDyQoXjnSB_bVQDE5kmphx6ON1nftN30SXO9qcGKiTCMAIbx9VibZeVNDLm_sP8sW-QzB2G0IF-6HOfqlybrliOl_OM6lHwZLv_J7aSWIpW8Djr_zE18eH-HsXJaj_0O6Jg2JPmuwd415yioxpOIhggIfxgRwLr-J5tKsHbLuKrCDCayYmfpA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE519EE982D156FEFBBA6019A5366EFE18CBCD6929114E		1
125	芯片中军之紫光国芯	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BJjTi0-oOltiEYkFP8aUe2FqXa8Fplpd9BWbpM6DdI2Zo4_3Srz-ikAP6GIRaHjlNxvHzoR8yZTDjw4l6yhbQKIZwnDq3UnuDDXptSjiJlsjnc3AjuvU7-28os2LW57ZG-Rm1dJCQ1zic_vsxWTVqkN458K3iW-jMtKB1kfNvP01bEgNgU2g_hvw522mGqI57_QUtxYDIsvm00NVofL2iDw..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE519EE982D156FEFBBA6019A5366EFE18CBCD6929114E		1
126	第一次使用国芯电脑	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BJjTi0-oOltiEYkFP8aUe2FqXa8Fplpd96sDAOMMi9FGedyWFyO3mqXgZ5xXKyZXywU_pwZdiz0YAJ2nS57KV9J3KeJ58GKzQbLt8_1ICVXTqavOJhOs9BAJEMk0_QFP36OHo_5gscTiC9608L3cU2NaueNUKZiwtoc-rogVMA4_5bKlTnCHu3VTB1FoUElvCar3BR0Ii6zYtPujwwRB2Pw..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE519EE982D156FEFBBA6019A5366EFE18CBCD6929114E		1
127	1月6日抱富指南:益客食品发行,国芯科技上市......	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BJjTi0-oOltiEYkFP8aUe2FqXa8Fplpd9NOf6ik0xDKGkHSTbGXRN3wPTpVJ-MYbX4fWwqpf0YMo09XXsQWyHZrP0-Epk737xc7rPBfoe6jsQo4WGsHHRvbabaqS7nD5ZTrh-yB0oShzjjuBCNJ8vj1yuSJunl0wQtoxXB9KxGnx8gYuFGKp2-hoDLEutoOEYXKgp9akqxu4NGbbB75bUeA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE519EE982D156FEFBBA6019A5366EFE18CBCD6929114E		1
128	【5月8日 第二百二十七场】甘肃国芯生物电子科技有限公司	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BJjTi0-oOltiEYkFP8aUe2FqXa8Fplpd9v-EIOKvOycndX7Qh18_FSjYrF9d10QeGhaVl9hLhsiiF_0y-USMOhMgOPmD8ORwzszMhXnqehrqeHIrtQ9rm5PggZMF8mnx4fjgGN5AIhH5v2WjaCbhnyjWJtzFOt26wWeRBtR_PEwocO8mk0DDZX-q3DRnKw5OjZ08IM69e2rk6Ebq8fk9diw..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE519EE982D156FEFBBA6019A5366EFE18CBCD6929114E		1
129	时隔八个月,“国芯大基金”又一人被查!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BJjTi0-oOltiEYkFP8aUe2FqXa8Fplpd9kXoZcmegCK6dbmhoAT-jDEMKkWXONT-2vltfMvXJqLBEBsRAaKOb_NDEYqBHLy_yzOopGEa6Fowb7_-O1xrxOOO4mpmXxs_rKzARu3mH6f_74UfOaHr7GrwcrnI1eNipd4URWzEXJK7rZA91ytglN2XE0oZ7n17DMXm3H1NbxIj6zvkPgoArRQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE519EE982D156FEFBBA6019A5366EFE18CBCD6929114E		1
130	研创·面孔 | 北联国芯:以“生态思维”筑牢信息技术应用创新产业根基	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Btekcs3tqKGqEYkFP8aUe2FqXa8Fplpd9hlnQqLnsj20lSJyZx392FuNYbb_NaE_IMhtlk09UaRTeWx83LUiLkUDph9HcLwFuxtqMgHb6o8qzCZ3pzriKvJk6OAju_ZUTeCz6xzSYEDP5C0sQDRFaGt0o1bkbskZX764nRaJrj2m5Z1HLqOG54mH70byY1tOxqhpji7ujbUXFcvUoAZZH7Q..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE5BC3BDD58602AAACEE374DDEE682AA3EAE6569291150		1
131	浙氪一周|杭州国芯科技、PingPong计划上市,零跑汽车获亿元B轮融资……	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Btekcs3tqKGqEYkFP8aUe2FqXa8Fplpd9jiQD90ag_ov0WfvH8nTnoiFh4fcTcI9ioshAM-4eVMr_lTEuoUtipiJyrstshTu56yvghRi0L2x5hzgJgzNbvJuEk60M-FejSXsllwL9d7nJ9exwN9ym8x2qR8tuZeM1F6BuoxXJzLta8sTV3xByD3TOJotaQk0w4uLycCU84A5r1dbZWbKUeQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE5BC3BDD58602AAACEE374DDEE682AA3EAE6569291150		1
132	国芯物联 | 加大自主研发力度,国内首款读写器自研芯片大规模商用	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Btekcs3tqKGqEYkFP8aUe2FqXa8Fplpd9LHW29n_yMWHNRoN1JLvhqidAWRj6N0xiJB_8El4vOUw2cfJCBoWb0ey871mm4fgGA-3KfpqvQZESrPU_N9XVXOvgsU1g8iliU86OBSj0U-4C-sQ_ossZYMov3oXtZ2UubwtHqbalzzWszXWlIBjT3kXsVnKts0LBn2AOf5q5R9QCYioxHkzTmA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE5BC3BDD58602AAACEE374DDEE682AA3EAE6569291150		1
133	一家设备商,被替换;8家中国公司被列入实体清单;苏州国芯被曝强制员工每天加班;联想手机要重回主流行列;淘宝转让苏宁易购全部股份	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Btekcs3tqKGqEYkFP8aUe2FqXa8Fplpd9qpfyJweM3y9k_jj-5oL2-mVHuXCtcOX_u3MuoNRgXwS5l7PFEdsU8wq63t9ah1d-LTTm6hwhs-1t2ddEIUFm3lw39BkqVjK9YdQITjwxd48nBILtzWVFTnKTALNcTDO24Wl93oGAHf0VFDSRNMoNuLaA6O2lY81iMMxAoTBnrqMNGbbB75bUeA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE5BC3BDD58602AAACEE374DDEE682AA3EAE6569291150		1
134	每日一芯 | 国芯科技汽车电子高性能MCU	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Btekcs3tqKGqEYkFP8aUe2FqXa8Fplpd9ZgeiB1BJq-bCq0kZbo84X34W_G9rlQCFSaThg_Cn7z2HDfVvXu-ihCPBV0k70qO09DTBDbiEXhLca2lbObvNis6On0YvyuydapZbV25n4JuZ_2QocBvT_1V4LES_j9gZUh93Mh0rN_HtgAcZNzqnwHDvJ_cnKO3P5n7QPPlchBPvzHZXxeLdyg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE5BC3BDD58602AAACEE374DDEE682AA3EAE6569291150		1
135	代言人国芯梦:台前光鲜亮丽的背后,是日复一日的坚持!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Btekcs3tqKGqEYkFP8aUe2FqXa8Fplpd9KyhfEftFwpbsbYrnsmuQHR-ui_-ofmhSWneekw0wWDmwkRnR802uaUrPrTh98lYRLTNbSaxsNZYzMxeplX_K1NORxosgXyPi5cWHtCd8KOGJMYe_3cn8ZWHc95XJH6as9kHxcM748XTIwxIwFiXChUZR9wX1U8jKNoiQEgEIBqKrCDCayYmfpA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE5BC3BDD58602AAACEE374DDEE682AA3EAE6569291150		1
136	省台聚焦→何以竹溪③:区域联动·共富路上的持续探索	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Btekcs3tqKGqEYkFP8aUe2FqXa8Fplpd9GU1w92hZkWoJTcpYNZYPGQb5ZNtUre3EI2eYk4uJ5QHmp9T6bRvezI0NlwdMZVQT0GSHG9X23whyotGEMn44q-qD8JEb9O3M-BUTQqzV6aIiOYhf-LKiWZo1mh4piUvIftIgWBECBQlOKRIvgpGwVZu3C2Lcetir3j1ar6wJiHXwdVqCwyPdzA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE5BC3BDD58602AAACEE374DDEE682AA3EAE6569291150		1
137	Bentley 软件携手北京华维国芯成立创新企业,推进工程管理数字化	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Btekcs3tqKGqEYkFP8aUe2FqXa8Fplpd9TwdxxxjHh_a0NCYG-uBXTFFijr5uxs8B5L1owrgrZoMxP0TBl48Ro7_aVnrijZ2yUN_Fm5dHBzrkn7isU8rcwcImVQQHfkwhNLthLiX1t0hfcXoxRQBV4OKEWiZTj-zLC81ccsNsHkGyAGP8twKrv_OM_DDMzCR-JoMlAEIgZjfy08OLTBhW0A..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE5BC3BDD58602AAACEE374DDEE682AA3EAE6569291150		1
138	最美乡村教育:林山国芯希望小学,小而美、小而精、小而优	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Btekcs3tqKGqEYkFP8aUe2FqXa8Fplpd9mf9jWDYEZsJ0Nrcv-wJ1GjclejDfVYTst4S4Zm7YhAxv7DQ8nK2W4Yv8S5a6xtnBh9giZejd-0V5-EkIrgtjP3IBZUjTKanbQ1gqisI9sHaaqRBWp4j6xU5ak-4O2gNWkAml6uS6eePMLYXu_Sq4f3rDurvdw0MH92emZe_UMogO8fIRwtipOg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE5BC3BDD58602AAACEE374DDEE682AA3EAE6569291150		1
139	省人大常委会调研组来溪开展专题调研	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_Btekcs3tqKGqEYkFP8aUe2FqXa8Fplpd9GU1w92hZkWoJTcpYNZYPGQb5ZNtUre3EI2eYk4uJ5QHmp9T6bRvezH1fToWRnc4SbVUQDg_o4WV0yihqcn_G02QoLOvU5eUaTUnpCBlWQRKGperpY8dOpBnr1UAJr_79wpCwsXLKK6kKvhULsyGv6VQ1uxnANe6XO7qXbHRuLFijotuuiAmOIg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE5BC3BDD58602AAACEE374DDEE682AA3EAE6569291150		1
140	No.185|3分钟看清一家护城河:国芯科技	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_B3AUj1N3x51-EYkFP8aUe2FqXa8Fplpd9kgLvqtIlDYPgHYSlVCIFH5lMIc72rBO2wBOwotYBEvC6H8J0bA1OsX7ALr9vB_Hc2iS3lR3LFPPLIxpZWGKuAgnbo5PZ-hnCBoqsB3KWrfDn5wukjaQfkSbh8eqviOCsmRytTyvKY36giPNILwI5I2F7yJa3HwYkniZgovH9ubMC2Qmj7RgGwQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE6B38294112953D3879A3DA9E39453EA9B45669291153		1
141	关于各位新老朋友关注【国芯在线】	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_B3AUj1N3x51-EYkFP8aUe2FqXa8Fplpd9oOeGW6jG2NBAHZpcsDcMw_IMjkUGKWgkcpC964o6D5HYr-9Cj7WgffummBz7otDSasjPVXn6vpffbersd42cpiXR4Dais-QYZQXUGeqTbWnn3xSamrtHWG0-gw6cOd7kN6iSJniCFx5zgUxrAIilkQfxdj2j72ma-wBN2jnoqFf0OK9DLfgmPA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE6B38294112953D3879A3DA9E39453EA9B45669291153		1
142	天地一体、国芯强基,遨游通讯闪耀2025中国国际信息通信展	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_B3AUj1N3x51-EYkFP8aUe2FqXa8Fplpd9z2obA_pzwnCTGqq5XO3fkRHnaevRIA_03ASYVVO6xWsTvIQY9ghyXW8iMJhRPPf2pm3Wem3MLkaiyQrG2R3FBfEHnuMQlDNtAD8UEfNxQk0HlTFR-pt_wvh_kXWL37pVHqgnckz2__hkeH3lQMmpYRPch_OWMfUnaxHLEm8Gdse00NVofL2iDw..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE6B38294112953D3879A3DA9E39453EA9B45669291153		1
143	低至70μW | 国芯发布超低功耗AI芯片,助力智能穿戴「芯」升级	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_B3AUj1N3x51-EYkFP8aUe2FqXa8Fplpd9TJGxzbkz3p4_AxCrD-yG_9tnTx8XcxUy5rGO6ACIx7VcsycbPLoPtVZMmQWgoQXajsAIg72TGzi-5K_8sq4co6LgqEsC-50_8WOl7rUsvvI8hqR-VOjdoRNF_VpLj3jj9X5A9HcRl0K6eROYPCqtt2uxCAbsPgKc1CF-CZLd1BQO8fIRwtipOg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE6B38294112953D3879A3DA9E39453EA9B45669291153		1
144	中企芯片订单飙升11倍!国芯迎来“猛兽”,外媒:一切就要结束了	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_B3AUj1N3x51-EYkFP8aUe2FqXa8Fplpd9lvO1Bf7QwmmeTpVnso25DZqq2rl2WmvY38WbMyFXZM64dpyppvBY4Ly4C4KHuvFWOhJDSwEwmuBmbUiGGBA2daiJBVSs5FeYqoTPunomgXQQrCpyYwpegVX8wK19p5a_kgnzjF7A0r2CG13qUTngErJ4ii5JzVXRwyFzrtBsrNx5Nu7CnoSqqg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE6B38294112953D3879A3DA9E39453EA9B45669291153		1
145	秦岭:绿色国芯 中央公园	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_B3AUj1N3x51-EYkFP8aUe2FqXa8Fplpd9XuAe-Kkwy9wJEmUfI1nYEmVwFMVJ2WPi9T1PxX8EuIGZOAyrtx1K4gshw9gO-fAvxiFIx3KkzY44PBoWR8XeVNlXHhDRfYyB2Wbj6DkS1jLmLoA6rnBh5HDLrXT3mJw1sB8MfgA9LCbeRSw4x7OnJT3dTvpfWcSDoEYvmrP5S5STJmCU1UgHwQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE6B38294112953D3879A3DA9E39453EA9B45669291153		1
146	一文了解量子科技概念及重点应用方向,一文梳理量子科技核心概念股(参照2025Q3末数据)	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_B3AUj1N3x51-EYkFP8aUe2FqXa8Fplpd9HW2NoQtxlyJsHJLSIa5uahYfbDjnSUxqXTU1s0ex2ceS4XEFFP0dHSN-tSueLtzlPxsu0UL7r2Re1mTcJcgXII_WXELzhbmcAk5HnjHigetaObcVQJeXExk1bVLVxnb8AspI3uLF_1mAMNiq7j3IrasYzyF77PNS1FOfbJ2KX8UY-UZGbO56rA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE6B38294112953D3879A3DA9E39453EA9B45669291153		1
147	TWS+AI?国芯发布超低功耗语音芯片,可能是目前最理想方案	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BLUcLUDizyk6EYkFP8aUe2FqXa8Fplpd9fXe9BHKlH6X2JgmT4qOxzKdsLp9V24lPwrv4JNDGUjW2ICvfRz3sSsFI1CZFVGnqcNAaMpXuhPBtCX0nzCiHyGKeb94EkB_S5FGGzI_9rgzf9o2wm5bj9C_5Seo9rdFW8yVpVhRDvZLapJrleWyvxDAsh3YRvpJkF2xlY2wfZ43S-e4Yz84xMA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE774ACFA4FB7CD7D19C493C1ABA08D8FFC2F269291155		1
148	再涨下去 4100点就亏完了——A股一周走势研判及事件提醒	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BLUcLUDizyk6EYkFP8aUe2FqXa8Fplpd9WRWl1WIN2WXqSZK7IUSCvFLG28Ny5bm3EZTge6_YexVyMvCrR_VJlDVJggOC1dtw7nxOd69__2ysmf8Iv3cETPVqWn_paAMpanqKihy2cy5oGSpCiAcJDGJFDatmkdzjvqRmardTMq0NJZh-L0yr7wgT5oNO9IiqFmK2Mf31b7O54z_tGSZTqA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE774ACFA4FB7CD7D19C493C1ABA08D8FFC2F269291155		1
149	和顺石油:奎芯科技赌上未来四年的荣誉,一场精密设计的换股并购	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BLUcLUDizyk6EYkFP8aUe2FqXa8Fplpd97MPGXy4o-DdTKPRIfNj4CuwWHGmVR0IZdBBHwkHSYlg9MDkSUMVuarGQ4_NLaau8mfE19uXVy_3nYr-MnmK-Ei0pTQ7lrxVst9PkOWyZm1nZ96Keayv5zVfIU_paS_c5Vqs--XcMq7aiHPbNliaNeoXN5gq5XJXUq9dvXJ_hHFnP28temKTOwg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE774ACFA4FB7CD7D19C493C1ABA08D8FFC2F269291155		1
150	祝各位工友:海外之旅,一帆风顺;辛勤付出,满载而归!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BLUcLUDizyk6EYkFP8aUe2FqXa8Fplpd9NzI3kU7kUxuuVAu6_oPTois2R-i0UWH8fDHDpkx5uBUvrbBSkqISRUqdQdSYCRvLzi-6B3_uw7zrsVbzwd2EX9TGF9FbOG9y4NARHc1QywlKYDMBTbiYZN18CkUm9ZkZEK_7xL6M1tFk-51Xp45QbfM6kOhoscy_1Ca0HPX9yNPYl_Q5RRZQjg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE774ACFA4FB7CD7D19C493C1ABA08D8FFC2F269291155		1
151	大干一百天 奋力夺全年 | 张庄街道:百日攻坚正当时 发力奋进夺全年	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BLUcLUDizyk6EYkFP8aUe2FqXa8Fplpd9QuvpQb1wyFs6NjnaS6TWyKt48CTREqjyO-QvJMi3boLfmr0EU016nvSa3DacRVjM2mzP99ZCEYEl4eIVsO0Osn75QtPoQebsGCId-5ccV0RyLU_jtElm2QbR1B6kj67l7Pq2x4_y-SovneMa5FZsRRSRCnQpKR9R55ue7WTsoytAe0f8bRARvQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE774ACFA4FB7CD7D19C493C1ABA08D8FFC2F269291155		1
152	通州、海门发布任前公示|一破产通企被国资接手|又一百亿项目获批|一周回顾	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BLUcLUDizyk6EYkFP8aUe2FqXa8Fplpd9J1KbCut5kU14WM4Ij6tcOh4Gngu-52sgAagTT5CsSBNu8rj7NyLLqcsHy6m_vwnYi65-BUJ7R6Km01LRWuWcHzTN5XBJ_tra5mg91cw-QeTCosfkjPWqpswRHScSGMuzcFbUjGqNokzvGSdo4aCJoUVIhKri9pH_rIY_4nlg6pJQL0Hr9Gyd3Q..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE774ACFA4FB7CD7D19C493C1ABA08D8FFC2F269291155		1
153	5月1号起施行!最高人民法院发布《关于第一审知识产权民事、行政案件管辖的若干规定》及配套文件(附案例)	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BLUcLUDizyk6EYkFP8aUe2FqXa8Fplpd9M45LbykFHqUbTRN5UIf8_R5aJ0Ek5LCVKPVgmy4jmko8xbVxHvEzKjTNxIwQ8UKqTiF8YAmmeoLRzpUoCKK22ZdNKmpW0D91Q0HxdxJT-qxcKgqFTiWUGwyuqDV6MBeXHhllKH1JveekCX5tYe9Lz4AOfsZW1joiYnekQr49ieHvzHZXxeLdyg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE774ACFA4FB7CD7D19C493C1ABA08D8FFC2F269291155		1
154	成都招聘 | 玩家的每一局,我们的每一局	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BLUcLUDizyk6EYkFP8aUe2FqXa8Fplpd90nI-OnSKC6PKVYQ6ePzUGcnlLqLulXjIP8zCZ-0RdA1iZwCHTAfnU7roRIn9SK5MimiYt3UpdKPBuMBM2dHryDXk62P2eyD8dxtulVURIW73b1Yk1xXMWoNDPSLcMR5DqCtoHRsPjefSlQOHAyr3OLjLofwNoWWfQ7tFRGg9w6EY-UZGbO56rA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE774ACFA4FB7CD7D19C493C1ABA08D8FFC2F269291155		1
155	国芯速递 | 基于纳祥科技高性能NX-FT422芯片的USB KEY硬件系统设计	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BLUcLUDizyk6EYkFP8aUe2FqXa8Fplpd9UizjCiRmYjkEOb1YA1RDrE-5jqCcpCm8lBGEtKWNBcJIYcFBg5jh_UUPnF6k9CDxC_VGw4t2s1Kqg9kvoSdfl1I-IAspBibcUUo8N5927yuSvJNoRLAZwL1b6PuSLB0d_vQ-BLcXIcMNwbr8gt8xxTLZy8A5jWSesxtfETpg26XI3OTRHYU2og..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE774ACFA4FB7CD7D19C493C1ABA08D8FFC2F269291155		1
156	邹桂香来溪调研生态环保和美丽乡村建设等工作	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BYbcetOb9OSuEYkFP8aUe2FqXa8Fplpd9GU1w92hZkWoJTcpYNZYPGQb5ZNtUre3EI2eYk4uJ5QHmp9T6bRvezK9CW4sWoqluRYytGV07JfPDd2nd2SaNXa7yGfqXlh-XobStmHAITPdluW6lyPlwLkGO_D0TcREb_fYtHuQo_U--T_lD9-jxmRbKK_yWxI9Y8PENg8hjh972CsG6-xMgzQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE85F05D3667E04B4C0FD4AFA29F324BEF3A3E69291158		1
157	自主国芯CPU第一股,即将上市科创板,另一个柘中+申通!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BYbcetOb9OSuEYkFP8aUe2FqXa8Fplpd9C3Bfl5TzZ19PDpGfSww1WtcT0apNK7Ott6jMR4B9UbBJcf58UhpRzk2uz_z5ps_p5jGJMSKC33Uo9Hgervtcmkr-pbM9wf615vpA--syEbqGmH-yNaJo_HsScPR00XUBleImWoaoWDJ52LsP0HaRWrGMLi04c5345TejR9nkPJrFcvUoAZZH7Q..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE85F05D3667E04B4C0FD4AFA29F324BEF3A3E69291158		1
158	驱动绿色智算 筑牢AIDC基石:华为携液冷热管理控制器TMU亮相2025CDCC大会	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BYbcetOb9OSuEYkFP8aUe2FqXa8Fplpd9vco9neS_zU4PLb4nMWbUaAJUCnLwdxlEF7lFwZGCORiqiwQJiJVATV1cS75HSaZzijOggsr6Syic2_JnLf2aKF0rX3dpnye8n2Xhyfsk5nbxaHkVEhMgQtZTmhl3U0f8v0mGiLaK_-fjcbBBPJyKIn4vJSdQ8RYSjpxrlm1FEpCfxjh3za6jWA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE85F05D3667E04B4C0FD4AFA29F324BEF3A3E69291158		1
159	「瞪羚企业」国芯,一家坚持自主创新的高科技公司,再获殊荣!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BYbcetOb9OSuEYkFP8aUe2FqXa8Fplpd9TJGxzbkz3p4_AxCrD-yG_9tnTx8XcxUy5rGO6ACIx7VcsycbPLoPtbOp0hptJMw0ollhNGZ_HhpSpRRY1PN5EXKjOXbTcAufFRAXlZz24DU3zLpmH1MxFUhUzYWYGlfw4KfjO-ROa9J2IcYFQ3Ny346xq9vIVyIRabzEXK7AD_5Ae0f8bRARvQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE85F05D3667E04B4C0FD4AFA29F324BEF3A3E69291158		1
160	讲好汽车芯片故事,国芯科技需在内卷中加一条战略定力	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BYbcetOb9OSuEYkFP8aUe2FqXa8Fplpd95Dzk1umbHPuzrSQW7xwDOs8JxyVnwC4lAv0ZgpswkQVWn-8NFQmc5K3RaXqebANyk0iEEcMKuYlZQAJY-Wi0Q4-PSddfzIkPuijiJnG1BvDhWuYGhwqU8eQLKK0Ug3h4PMqDHOLvVD4eiEksabeTwGy3b1bjqz5IumMcp-x6oIF535pjGOOjYg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE85F05D3667E04B4C0FD4AFA29F324BEF3A3E69291158		1
161	国芯科技总经理戴小平一行拜访启迪控股总部	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BYbcetOb9OSuEYkFP8aUe2FqXa8Fplpd9E5w__PjmXG2B8KsGvY7fr7a_XPg966oJ-lJctr5erf09_pLY-R1x7FUFduAvEALRdYX8BfbHDIvsMjj8nKzGzIhqaAnDM9GJr4lY4a19ehuUJgQpZtux4X6NMIPjYPYTXKP7pPe6coJJXG2sTceX7wUNeUI0p4EWBupUxSNPtyfzAjcIGepUqA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE85F05D3667E04B4C0FD4AFA29F324BEF3A3E69291158		1
162	合肥,一个“伪装成城市的投行”	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BYbcetOb9OSuEYkFP8aUe2FqXa8Fplpd9F3zwUnt7ue82kRXFRprxiyJDFHwwrIhZ85c3TbKoXCwWtG4LF6MiJ-pcQ1SUif_6ZUsZV_vzEHCYGEKN02cp5NwMrhLxOLkcIRgtv0xhiRw7JElKkTJwyBWVqBidXevmXijpj0p7gCqaLw_pNVfNWgws3IUXUuKHxLv7XhDV63ZS6t2rFt2rnA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE85F05D3667E04B4C0FD4AFA29F324BEF3A3E69291158		1
163	深圳,下一个新加坡? | 檀财经	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BYbcetOb9OSuEYkFP8aUe2FqXa8Fplpd9WvefrX8zLqQQ1EoKSA1n0bEHcFuzlTpKr6FbzhkNszY0Mgx2tyTSVGTUta9dpOj6CZ3awwaaQ5CIduWCP5AoeSG3GddavMWDvo1SwuEB8D859dBitezVoZfIfueyQ0xxwXLZXNvzUVHkQ6zQS3Y2xvGjFSUxAy0cZ_iFholqM91FkDr8IT4KYw..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE85F05D3667E04B4C0FD4AFA29F324BEF3A3E69291158		1
164	【硬件资讯】国芯当自强!龙芯最新产品发布,性能大幅提升,终于来到了主流性能梯队了吗??	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BYbcetOb9OSuEYkFP8aUe2FqXa8Fplpd9X-sL87OlpDRmaefOiLfOd-Ye1Iy77DGVvDyUIfMLXt_C6AOr0EbmcSpM37x-ZbIH0NUEcbafC7Y2-fAIqYa6SfSVlAxwY7B0bufs5lBlA3RYilVFMZ6ae1IlAdGxPw8gXTlHp8NAFtvUy5PLy11HBShyS5g31eeskj3Mv-2L9Q1flztgI7RZ1g..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE85F05D3667E04B4C0FD4AFA29F324BEF3A3E69291158		1
165	三一重工为什么股价比徐工高?差一个东西就差了一个太平洋	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BYbcetOb9OSuEYkFP8aUe2FqXa8Fplpd9WvefrX8zLqQQ1EoKSA1n0bEHcFuzlTpKr6FbzhkNszY0Mgx2tyTSVBVbUp3vlPBrJR7a-_4N0X3MQN1c31s00UwtHZerkvfOsmr8emXsLoYbQ2P12i49HTavp0JM3aJL7_txsF4u3FIvCj2A9dHGjzBl3kGpQHFqwf73L8hy7QlS6t2rFt2rnA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE85F05D3667E04B4C0FD4AFA29F324BEF3A3E69291158		1
166	十堰百名干部深圳研学活动纪略	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BamgBU5NNY0mEYkFP8aUe2FqXa8Fplpd9pOglinXhB3lmOfNhVtmhQrFqsHxwnR1uahH4lGw1xtY8D6LWiIggMGt41j4yTyBEj2k8-qRfGhOtt-nm4RL8zH-G9BFBkgoZM8rMS52ge6Dh-mw3vNOp0RepiFbV7-8lT3mZrPYEy_6IJ_UQvVVA1hw7INjTKkGJYKmwaAJnKAk6Ebq8fk9diw..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE94D1771D4CCA606725FF84747099619157EB6929115B		1
167	12.12脱单预告!双流区总工会牵线,赴一场双向奔赴的甜	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BamgBU5NNY0mEYkFP8aUe2FqXa8Fplpd9DddhfQKRlhnfT25UU98eTlAv4c_T25EypXwH9Cqkism0UG9tbFGuJICS1zRgRiQVKETqZANtHTKZVogXhG5kWkKoa7cBa0K2sffsrgtL14im0F8LUoCcVif_-kJPIt49KGVOuUfhRAgFXKxFUXl_MiI37vzEMPhNvUJT1WVBRfry08OLTBhW0A..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE94D1771D4CCA606725FF84747099619157EB6929115B		1
168	小小少年,扬帆起航——国芯希望小学第一周值周小结	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BamgBU5NNY0mEYkFP8aUe2FqXa8Fplpd92N8ORNdfOgmnJfik727QS5ehiyL2NIYYp-uG5IbdVrjFfgsqEW81kiQAKSzMc6OClJZhZMe3bnOrEww7rTlPaBCSBTplY_yAhLnp3m6zIB6NEUJ9Yk-_1Akbe0DYihZXPU4dXULwlQRS1-Em7e16K8PDkG4cHrZZbuiv-mP9BoVf_71bqkOtiw..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE94D1771D4CCA606725FF84747099619157EB6929115B		1
169	谁是下一个“独角兽”?	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BamgBU5NNY0mEYkFP8aUe2FqXa8Fplpd9_deAnla0vZBjWcA3RwLF98NRgbFgrNNaBvzAOjXi-Hz19azzi4l6ZAWrMRxLDTEPnQo-aFKcfTo5xZeTqp31XwkfRKg2HsQ9qDMIhntVX5RgW9iGrhY8LEIg-H7d_D80Pj1J_zfODMitvGaxwfmwzfl56ZGxmD46p2Nk2vworBaTJmCU1UgHwQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE94D1771D4CCA606725FF84747099619157EB6929115B		1
170	赛迪四川甄选·新能源汽车行业(一)丨新能源汽车驱动城市竞争格局迭代	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BamgBU5NNY0mEYkFP8aUe2FqXa8Fplpd9IP75zIdVnc8-4YSt-La10O0VaXZQLvN0O53P16jB6cV6oUeUqJjFagTjQMEnVV32NuIUGoOhZeIVjmFEs_PIW-UE2YE8j31_eMrA0gUYyuSwCfVUhAKJYl-IyaEZmgrSwwLpaco2WnKOrgvIwCrJGv56MIZcK1yEJfwDdKLnGDDRtmyIGw2VAg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE94D1771D4CCA606725FF84747099619157EB6929115B		1
171	炎黄国芯、涞澈科技等13个金奖颁出 在青岛他们将再次扬帆起航	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BamgBU5NNY0mEYkFP8aUe2FqXa8Fplpd96NI-GsK1Ihs62eW7lPEYxnDnC9flUa1njn8KoEYNQ-eC_cCaeNejA38qW8tH6MYhwCipFzYJ4uPnUrkbSF4gQB5Ck-_XM0jzlwimU0fahvHFYWWKfBgZNCRuEoJ5saX0_y21aGMKDsZ9x1IsgvkAKl7-jxNunRGfPrUQJ9igURvS-e4Yz84xMA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE94D1771D4CCA606725FF84747099619157EB6929115B		1
172	全球首个!中国自研沙尘预报AI模型试运行	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BamgBU5NNY0mEYkFP8aUe2FqXa8Fplpd9DgDyQoXjnSB_bVQDE5kmphx6ON1nftN30SXO9qcGKiTCMAIbx9VibcLgoOwdPPPIYp0lEgm-VC6Ncpj81oWdw1mYq_sAgOtSqW7g4vTJUqtmCi_gTYes3YmYco_2QYhAuTHLKuADx69Td-stybS3dqNbvhlhGLMhm96SNurmpt5e0WC6Sbi7DA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE94D1771D4CCA606725FF84747099619157EB6929115B		1
173	再次分享5G、国芯干货	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BamgBU5NNY0mEYkFP8aUe2FqXa8Fplpd9row0xtKOQ6QNcVAziRGFT7ObXNS2dUEwGlgAG-icjI1uozfKlSZgqJM95lqGZxvZSCpqdgh5PpqrShsSDJ3T_OU-bLJl2lYMwhRnsRl7EvNKQUB_dTc4vI4GGiYq2i5s_GfR-uCLP0Lrl4cdfcR0Iogq1s2T1kHcFLbdYlsVHan1AfaFW2DefQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE94D1771D4CCA606725FF84747099619157EB6929115B		1
1	湖北再添算力中心！竹溪“国芯一号”智算中心正式上线	https://sjj.hubei.gov.cn/bmdt/sxdt/202410/t20241017_5374762.shtml	“国芯一号”由科大讯飞携手华为助力建设，总体规划200P算力，一期建设50P，并利用区域智算中心底层算力及算法的资源训练、推理场景模型，助力竹溪建设以智算 ...	0
2	竹溪“国芯一号”一周年：算力为基，县域经济“乘势跃升”启新程	https://zhuanlan.zhihu.com/p/1963578610129536536	“国芯一号”智算中心作为全栈自主创新的智能算力枢纽项目，依托昇腾算力与讯飞“飞星一号”架构，实现了从硬件到软件的全面自主创新。这不仅提升了智算中心的 ...	0
3	“国芯一号”智算中心上线：“算力+大模型”助力产业发展	https://www.stdaily.com/web/gdxw/2024-10/25/content_248295.html	科技日报记者李禾. 近日，“国芯一号”智算中心（以下简称智算中心）在湖北省十堰市竹溪县上线发布，竹溪将以“智算中心+特色行业大模型”推动AI产业加速发展 ...	0
4	“国芯一号”智算中心正式上线，科大讯飞与竹溪共筑算力未来	https://finance.sina.com.cn/roll/2024-10-15/doc-incsruvt0739138.shtml	“国芯一号”由科大讯飞携手华为助力建设，总体规划200P算力，一期建设50P，并利用区域智算中心底层算力及算法的资源训练、推理场景模型，助力竹溪建设以智算 ...	0
5	2024秦巴算力峰会暨“国芯一号”智算中心上线发布会举办	http://www.banyuetan.org/dfgc/detail/20241012/1000200033136151728716399929185368_1.html	竹溪“国芯一号”智算中心总体规划200P算力，一期建设50P国产化算力底座，并充分利用区域智算中心底层算力及算法的资源训练、推理场景模型，打造以政务、文旅、 ...	0
6	重磅！“国芯一号”将于10月15日正式上线（附：算力科普）	https://www.sohu.com/a/815943105_178311	重磅！“国芯一号”将于10月15日正式上线（附：算力科普） ... “算力”究竟是个什么力？ ... 全球都在疯抢算力。 与此同时，算力也正在成为世界各国科技角逐的主赛场， ...	0
7	“国芯一号”智算中心在湖北竹溪上线_央广网	https://tech.cnr.cn/techph/20241025/t20241025_526952617.shtml	国芯一号智算中心位于湖北省十堰市竹溪县数字经济产业园，园区整体规划面积约70.5亩，建筑面积62882平方米，包含国芯一号智算中心、AI研学基地，产业创新中心及其配套 ...	0
8	“国芯一号”智算中心助力竹溪县域经济创新发展- 十堰	http://news.cjn.cn/hbpd_19912/sy_19931/202411/t5028647.htm	“'国芯一号'是基于竹溪县产业特色量身定制的算力底座。”刘啸表示，竹溪县在政务、文旅、农业等方面积累了相当丰富的数据，智算中心将重点打造政务和农业两大核心应用场景， ...	0
9	竹溪速度！“国芯一号”智算中心一期50P国产化算力底座正式投入运营 ...	https://caifuhao.eastmoney.com/news/20250317110301873326310	2024年10月15日，在地处中国雄鸡版图心脏位置的竹溪县，由科大讯飞携手华为建设的“国芯一号”智算中心正式上线。“国芯一号”采用华为昇腾芯片与科大讯飞“飞星一号”智能算力 ...	0
10	“中国心”用上“中国芯”，智算中心落户湖北竹溪助力绿色发展	https://www.ctdsb.net/c1676_202410/2279289.html	“国芯一号”由科大讯飞携手华为助力建设，总体规划200P算力，一期建设50P，并利用区域智算中心底层算力及算法的资源训练、推理场景模型，助力竹溪建设以智算 ...	0
11	“中国心”用上“中国芯”，智算中心落户湖北竹溪助力绿色发展	https://www.ctdsb.net/c1676_202410/2279289.html	“国芯一号”由科大讯飞携手华为助力建设，总体规划200P算力，一期建设50P，并利用区域智算中心底层算力及算法的资源训练、推理场景模型，助力竹溪建设以智算 ...	0
12	中美半导体巨头和解！“国芯一号”崛起！	https://www.bilibili.com/video/BV1Gv421i7yU/	bilibili官网. 登录. 下载App. 打开App，流畅又高清. 中美半导体巨头和解！“国芯一号”崛起！ 博乐钢哥. 相关推荐. 查看更多. 华为“神农大脑”横空出世！10秒看病，堪 ...	0
13	竹溪国芯一号智算中心上线农村新报	https://ncxbepaper.hubeidaily.net/pad/content/202410/12/content_291115.html	湖北日报农村版讯（记者庹文佳、通讯员郭浩）10月11日，从2024秦巴算力峰会暨竹溪县“国芯一号”智算中心上线新闻发布会上获悉，项目于9月20日开工，主要 ...	0
14	竹溪“国芯一号”智算中心正式上线！#2024秦巴算力峰会#数字经济	https://m.douyin.com/share/video/7425948789774486794	竹溪“国芯一号”智算中心正式上线！#2024秦巴算力峰会#数字经济#新质生产力（ 视频拍摄、剪辑：冯昊） - 竹溪县融媒体中心于20241015发布在抖音，已经收获了152个喜欢， ...	0
15	约2.86亿元！竹溪县数字经济产业园一期 ...	https://www.dtdata.cn/index.php?c=show&id=2302	据公告所知，竹溪县数字经济产业园一期（竹溪县国芯一号智算中心）项目（EPC）已由竹溪县发展和改革局以备案证批准建设，项目业主为竹溪县碧轩生态科技有限公司， ...	0
16	湖北竹溪“国芯一号”智算中心上线	http://www.jjckb.cn/20241018/55daf1ac40d747279193f77c60bb94c1/c.html	据介绍，“国芯一号”智算中心是一座全栈自主创新算力底座，由科大讯飞携手华为助力建设，总体规划200P算力，一期建设50P，将在数字经济发展、区域协同、绿色可持续和技术 ...	0
17	“国芯一号”智算中心一期50P国产化算力底座正式投入运营	https://finance.sina.com.cn/stock/relnews/cn/2025-03-17/doc-inepxqht3731001.shtml	“国芯一号”采用华为昇腾芯片与科大讯飞“飞星一号”智能算力平台，实现硬件、软件、调度系统全链路自主研发。	0
18	竹溪县数字经济产业链招商成功签约14个项目竞逐县域发展新赛道	http://m.10yan.com/m/showArt.html?contentid=947328	据介绍，“国芯一号”智算中心上线一年来，已吸引科大讯飞、中科星图等10家企业落户，助推竹溪县域数字经济规模攀升至12亿元。一批契合本地需求的数字化解决 ...	0
19	秦巴数字经济产业研究院在竹溪揭牌-湖北汽车工业学院	http://www.lianpp.com/huat/info/1087/22688.htm	本网讯（文/王礼华）10月18日，秦巴数字经济产业研究院在竹溪县正式揭牌。 · 当天，竹溪数字经济产业链招商暨2025“国芯一号”生态合作伙伴大会同期在竹溪县桃花岛夯土小镇举行。	0
20	“竹溪”模式，算力驱动的一场县域数字经济突围	https://www.163.com/dy/article/K7J4GPDJ05118A91.html	“国芯一号”的成功实践表明：县域发展数字经济不在于规模大小，而在于能否找到合适的切入点，将先进技术与本地特色有机结合。而26家生态企业的入驻，证明了这个 ...	0
21	【竹溪县中心】竹溪县数字经济产业园一期（竹溪县国芯一号智 ...	https://bidcloud.llb.chutianyun.gov.cn/hubei/jyxx/004001/004001006/20240731/37cde1ba-bff7-4858-b250-bb1b56c8aec0.html	【竹溪县中心】竹溪县数字经济产业园一期（竹溪县国芯一号智算中心）项目（EPC）项目报建公告(项目编号HBZH-202407QG-012) ; 总投资额（万元）, 28600.0 ; 立项 ...	0
22	【竹溪县中心】竹溪县数字经济产业园一期（竹溪县国芯一号智 ...	https://hbbidcloud.cn/hubei/jyxx/004005/004005006/20240829/6c599a9c-046a-4719-8e47-1b728eba92d5.html	【竹溪县中心】竹溪县数字经济产业园一期（竹溪县国芯一号智算中心）项目（EPC）竹溪县数字经济产业园一期（竹溪县国芯一号智算中心）项目（EPC）中标结果公告(标 ...	0
23	竹溪新闻网-2024秦巴算力峰会暨“国芯一号”智算中心上线发布 ...	http://www.zxxww.com/show-187-141278-1.html	2024秦巴算力峰会暨“国芯一号”智算中心上线发布会将于10月15日在竹溪县桃花岛夯土小镇举办. 2024秦巴算力峰会暨“国芯一号”智算中心上线发布会将于10 ...	0
24	湖北竹溪“國芯一號”智算中心上線	http://big5.news.cn/gate/big5/jjckb.xinhuanet.com/20241018/55daf1ac40d747279193f77c60bb94c1/c.html	據介紹，“國芯一號”智算中心是一座全棧自主創新算力底座，由科大訊飛攜手華為助力建設，總體規劃200P算力，一期建設50P，將在數字經濟發展、區域協同、綠色可 ...	0
25	武汉中汉飞龙科技助力竹溪数字经济产业发展	http://www.hbafxh.org/caseShow_3956.html	截至目前，“国芯一号”已吸引科大讯飞、中科星图等10家企业落户，并与天融信、裕豪万通等27家企业达成算力合作，推动县域数字经济规模攀升至12亿元。本次大会 ...	0
26	校长彭瑜带队赴竹溪开展乡村振兴调研深化校地协作共促 ...	https://www.wbu.edu.cn/2025/1110/c124a83620/page.htm	调研期间，彭瑜一行先后深入蒋家堰镇关垭子村、“国芯一号”中药材种植基地、竹溪县茶叶交易市场及水坪镇前进村等地，实地考察乡村特色产业发展、文旅 ...	0
27	科大讯飞华为联袂：竹溪'国芯一号'点亮数字经济未来！ ...	https://emcreative.eastmoney.com/app_fortune/article/index.html?artCode=20241016194639821428130&postId=1471166832	竹溪“国芯一号”智算中心的正式上线，标志着这个位于中国腹地的小城正迈向数字经济的新高地。科大讯飞和华为强强联手，共同打造这一拥有200P总规模的算力基地，一期建设 ...	0
28	竹溪县数字经济产业链招商签约超亿元，竞逐县域发展新赛道	https://news.qq.com/rain/a/20251018A068EM00	目前，“国芯一号”已吸引科大讯飞、中科星图等10家企业落户，与天融信、裕豪万通等27家企业达成算力合作，推动县域数字经济规模达12亿元。	0
29	向着AI产业“换道超车”，湖北竹溪“国芯一号”智算中心上线	https://www.ctdsb.net/c1673_202410/2289889.html	竹溪“国芯一号”智算中心由科大讯飞携手华为助力建设，总体规划200P算力，一期建设50P全栈自主创新人工智能算力底座。在算力硬件层面，采用了华为先进的“昇腾” ...	0
30	2.86 亿大单、竹溪县国芯一号智算中心	https://www.163.com/dy/article/J8FB03RE0511D6RL.html	2024 年7 月31 日，竹溪县碧轩生态科技有限公司发布《竹溪县数字经济产业园一期（竹溪县国芯一号智算中心）项目（EPC）》招标公告。	0
31	国芯一号”智算中心助力竹溪县域经济创新发展_数字	https://www.sohu.com/a/826848705_178311	近日，记者在位于竹溪县数字经济产业园的“国芯一号”智算中心无尘机房里看到，一排排智算机柜整齐排列，正进行复杂的大数据分析与云计算服务。	0
32	竹溪县数字经济产业园一期（竹溪县国芯一号智算中心）项目 ...	https://www.hbbidcloud.cn/zhuxi/zbygg/20240719/3a3acfbc-292b-480a-9448-2e2dccff17a5.html	项目名称：竹溪县数字经济产业园一期（竹溪县国芯一号智算中心）项目（EPC） · 项目单位：竹溪县碧轩生态科技有限公司 · 合同估算价：约29000万元 · 计划招标时间： ...	0
33	2024年10月全国43个智算中心最新进展	http://idce.com.cn/news2.asp?id=3469	10月15日，2024秦巴算力峰会暨“国芯一号”智算中心上线发布会举行。此项目由科大讯飞携手华为助力建设，总体规划200P算力，一期建设50P，并利用区域智算中心底层算 ...	0
34	搜索_经济网_人民日报中国经济周刊官方网站	https://app.ceweekly.cn/pc/index/search?keyword=%E8%AE%AF%E9%A3%9E	“国芯一号”上线一周年交出亮眼答卷，助竹溪县域数字经济再上新阶. 本次大会由中共竹溪县委、竹溪县人民政府主办，竹溪县数据局、湖北昶禾资本运营集团公司承办，华为 ...	0
35	连接开发者与智能计算生态	https://aijishu.com/channel/server/tag/data-center	地处中国版图心脏位置的竹溪县，携手华为与科大讯飞建设的“国芯一号”智算中心已于2024年10月正式上线，实现了硬件、软件、调度系统的全...	0
36	2024年智算中心建设回顾：隐忧浮现	https://www.doit.com.cn/p/525558.html	总体规划200P算力的竹溪国芯一号智算中心10月15日投入运行。一期建设利用区域智算中心底层算力及算法的资源训练、推理场景模型，打造50P智算运营中心 ...	0
37	2025年10月18日AI与数字经济狂欢：新电商生态重构进行时	https://news.softunis.com/46082.html	从湖北竹溪“国芯一号”算力生态圈的崛起，到阿里国际站AI助手重塑跨境贸易；从腾讯3D世界模型开源赋能工业仿真，到小鹏人形机器人“灵驹”量产降价……政策、技术 ...	0
38	提质向“新”： 湖北全力构筑中部崛起“数字引擎”	https://fzzx.jl.gov.cn/tszs/202509/t20250903_9314957.html	... 国芯一号”智算中心均已投运，孵化文旅、农业、政务、安全等行业大模型，服务当地产业智能化转型与升级。 以点带面，全业融合。从医疗领域AI诊断准确率 ...	0
39	竹溪县碧轩生态科技有限公司	https://www.qcc.com/firm/3097a1c4d16119b38ee8ae2bb1cebff3.html	国芯一号. 湖北国芯一号科技有限公司. 股权结构. 法定代表人. 吕晓辰. 注册资本. 1000万元. 认缴出资额. 800万元. 持股比例. 80%. 成立日期. 2025-10-16.	0
40	华为中国行2025·湖北新质生产力创新峰会成功举办	https://www.cpnn.com.cn/qiye/jishu2023/202508/t20250821_1826033.html	... 国芯一号”智算中心、武汉东西湖“网安基地智算中心”均已投运，孵化文旅、农业、政务、安全等行业大模型，服务当地产业智能化转型与升级。 华为湖北政企 ...	0
41	【中华网】邝远平率队赴十堰多地考察助力“楚商回乡共建支点”	https://www.52hrtt.com/lsj/n/w/info/G1749120220701	随后，来到竹溪智算中心“国芯一号”项目基地，对竹溪县在人工智能数字经济产业领域的布局表示赞赏。 在竹溪县招商中心召开的政企座谈会上，竹溪县委 ...	0
42	湖北汽车工业学院	https://www.huat.edu.cn/ssjg.jsp?wbtreeid=1001&searchScope=0&currentnum=13&newskeycode2=	... 国芯一号”生态合作伙伴大会同期在竹溪县桃花岛夯土小镇举行。国家相关部委、省市有关领导、行业专家及企业家代表近200人齐聚，共话数字经济发展路径。我校. 【迎评进行 ...	0
43	产经观察丨湖北算力规模领跑中部：智算撑大梁，供需失衡待 ...	https://finance.sina.com.cn/jjxw/2025-07-09/doc-infewkcp2708274.shtml	... 国芯一号”智算中心算力底座赋能十堰“绿色基因”…… 算力，是数字经济时代的核心生产力。据中国通信院测算，算力每投入1元，将带动3-4元的GDP增长。 近年 ...	0
44	IT设备	http://www.dcworld.cn/news/idczx/	竹溪“国芯一号”一周年：算力为基，县域经... 2025-10-20 17:57:33. 深度评测：Aginode安捷诺网络布线产品全方位解析. 2025-10-20 17:25:17. “全链更安全智算赢未来”2025 ...	0
45	考拉悠然的人工智能操作系统是自主研	https://ir.p5w.net/question/00010E84F9B7580F42CC9FA5B79B036D6A50.shtml	... 国芯一号”生态合作伙伴大会。考拉悠然计划在“国芯一号”智算中心投入150P算力进行大模型开发，进一步完善“基础设施-技术研发-场景应用”产业链条。此次签约是公司践行“多 ...	0
46	2024秦巴算力峰会暨“国芯一号”智算中心上线发布会举行	https://www.sohu.com/a/816874865_178311	罗耀华在致辞中说，“国芯一号”智算中心在竹溪成功上线，将为十堰市乃至秦巴地区的数字经济发展提供强大的核心支撑。省数据局将继续在政策和技术上加大 ...	0
47	关注地方两会丨十堰：着力打造绿色智造之城	https://www.cenews.com.cn/news.html?aid=1197047	推进国芯一号智算中心二期、工业基地通信枢纽等项目建设，争取武当云谷融入东数西算一体化算力网。推进车路云一体化试点建设，完成车载终端推广、路侧 ...	0
48	竹溪县抢占创新“新赛道”增强发展新动能	https://xn--wlqu0hxn21nvsvf9w.net/HZCWeb/News/Details?id=8B4FC5CAE3D042648720473DBEF42435	加快数字经济产业园二期建设，全力争取科大讯飞、中科星图卫星地面站等在谈项目签约落地，打造鄂渝陕毗邻地区算力中心。并以“国芯一号”智算中心为中枢，全面 ...	0
49	【AI早点】2025年10月25日星期六丨县域版	https://m.10100.com/article/28321479	竹溪县“国芯一号”智算中心带动数字经济. 新闻要点：竹溪县“国芯一号”智算中心一期建成50P算力，孵化3个智慧茶园（带动茶叶销售额14亿元）、“随溪问 ...	0
50	校领导带队赴竹溪县深化校地合作-汉江师范学院 - 雅虎体育直播	http://mangaowy.com/info/1046/9857.htm	... 国芯一号智算中心、竹溪县外国语学校走访调研、访企拓岗，并与竹溪县教育局、竹溪县第二高级中学相关负责人开展交流座谈。 5月10日，付永昌、周明华 ...	0
51	数字经济升级	https://news.softunis.com/tag/%E6%95%B0%E5%AD%97%E7%BB%8F%E6%B5%8E%E5%8D%87%E7%BA%A7	从湖北竹溪“国芯一号”算力生态圈的崛起，到阿里国际站AI助手重塑跨境贸易；从腾讯3D世界模型开源赋能工业仿真，到小鹏人形机器人“灵驹”量产降价……政策、技术、场景三重 ...	0
52	武汉中汉飞龙科技助力竹溪数字经济产业发展 - 360足球直播	http://fr.pictaps.com/caseShow_3956.html	10月18日，湖北十堰竹溪县在桃花岛夯土小镇成功举办竹溪数字经济产业链招商暨2025“国芯一号”生态合作伙伴大会。近200位行业专家和企业家深入秦巴山区， ...	0
53	湖北竹溪农商银行为创新赋能助力科技型企业发展	http://www.zhgnj.com/yh/2024-11-05/A1730707889262.html	近期，2024秦巴算力峰会暨“国芯一号”智算中心上线发布会在竹溪县举办，标志着“国芯一号”智算中心正式落户竹溪县。作为“国芯一号”项目的合作企业，湖北 ...	0
54	财经_华南财经网	https://www.huanancj.com/m/list.php?tid=179&TotalResult=2380&PageNo=58	“国芯一号”上线一周年交出亮眼答卷，助竹溪县域数字经济再上新阶. 时间：2025-10-20 22:56:41 栏目：国内财经 · 首页 上一页 下一页 末页 共238页2380条. 电脑版 - 免责 ...	0
55	企业数据中心_中国IDC圈	https://dc.idcquan.com/index6_32.shtml	竹溪“国芯一号”一周年：算力为基，县域经济“乘势跃升”启新程 · 4. 数据港总裁王信菁：算力的价值，在“绿色”中见真章 · 5. 得瑞领新亮相2025云栖大会，以存储创新筑牢云+AI ...	0
56	2025年1-3月88条数据中心项目汇总	https://zhuanlan.zhihu.com/p/1890435067341431967	... 国芯一号智算中心）项目. 50、【湖南】中国电信衡阳智算中心一期建设工程. 51、【海南】中国电信海南（三亚）国际信息园一期项目. 52、【海南】海南澄迈 ...	0
57	算力赋能县域发展！ 竹溪数字经济产业链招商签约超亿元	http://m.10yan.com/m/showArt.html?contentid=947271	10月18日，竹溪县举办数字经济产业链招商暨2025“国芯一号”生态合作伙伴大会。近200名行业专家、企业家齐聚秦巴山区，共话算力赋能县域发展路径，现场 ...	0
58	【“强国行”专项行动】2025年度“中国调查·社科强县计划”项目组 ...	http://www.lianpp.com/huat/smu_jgxy/info/1157/5488.htm	... 旅融合、特色农业链延伸等议题开展座谈。调研组还实地考察了竹溪国芯一号智算中心、湖北大卫投资有限公司和湖北凯泽鑫电子有限公司等三家企业。望甜...	0
59	竹溪“算力革命”：一场县域经济的数字突围战	https://news.softunis.com/46088.html	2024年，当地政府联合华为、科大讯飞打造的“国芯一号”智算中心正式投运，一期50P算力（FP16）迅速被农业遥感、政务AI等场景消化。更令人瞩目的是 ...	0
60	E企研究院- 极术社区- 连接开发者与智能计算生态	https://aijishu.com/u/e7research	在“国芯一号”智算中心上线一周年之际，竹溪县召开了竹溪数字经济产业链招商暨2025“国芯一号”生态合作伙伴大会。通过此次大会，看看竹溪“国芯一号”到底交出了怎样的答卷？	0
61	填补行业空白，科大讯飞助推“智算运维标准化”建立	https://www.china-news-online.com/h5/index/newDetail?id=77303	在竹溪，“飞星一号”为“国芯一号”注入新动能。全栈自主创新算力底座，为竹溪政务大模型、农业大模型等提供了算力“温床”，助力政务、农业、文旅研学等 ...	0
62	总规划算力14400P！武威智算中心项目T1智算中心楼封顶	https://www.dtdata.cn/index.php?c=show&id=2300	... 国芯一号智算中心）项目（EPC）启动招标. 相关推荐. 总投资约14.8亿！泉州两岸数据要素全生态产业园项目（含智算中心）正式施工. 项目位于福建省泉州市丰 ...	0
63	湖北竹溪县：拥抱绿水青山，逐梦金山银山	https://news.ifeng.com/c/8f1FYulixGW	... 国芯一号”智算中心，签约算力合作企业26家，已初步实现财政收入1350万元，全面建成达产后预计产出经济效益13亿元。提前谋划低空经济，无人机项目组装 ...	0
64	党群工作 - 永乐高ylg888888|集团首页	https://www.j-nut.com/info/1157/5483.html	课题组还实地走访了竹溪县产业一线，重点考察了竹溪国芯一号智算中心、湖北大卫投资有限公司和湖北凯泽鑫电子有限公司三家企业。 2025年度“中国调查 ...	0
65	05-12 2025 校领导带队赴竹溪县深化校地合作5 ... - 博鱼体育登录	https://www.directsatisfied.com/info/1046/9857.htm	... 国芯一号智算中心、竹溪县外国语环球360会员登录走访调研、访企拓岗，并与竹溪县教育局、竹溪县第二高级中学相关负责人开展交流座谈。 5月10日，付 ...	0
66	品牌营销新趋势朝闻通助力企业精准发声	https://www.zhaowenpress.com/dynamic/cwdt/19525.html	“国芯一号”上线一周年交出亮眼答卷，助竹溪县域数字经济再上新阶. 2025-10-20 09:31. 91. 微信客服. 微信在线咨询; 400-880-0046; info@przwt.cn. 联系我们 ...	0
67	工信部：适度超前建设发展算力网络等新基建	http://jixietop.top/thread-58525-1-1.html	7月31日，竹溪县人民政府网站发布《竹溪县数字经济产业园一期（竹溪县国芯一号智算中心）项目（EPC）》招标公告。 该项目位于湖北省十堰市竹溪县，合同估算28600万元 ...	0
68	思特奇：参股公司考拉悠然参与竹溪数字经济招商签约	https://news.futunn.com/en/post/64260902	... 产业链招商暨“国芯一号”生态合作伙伴大会。考拉悠然计划在“国芯一号”智算中心投入150P算力进行大模型开发，进一步完善“基础设施-技术研发-场景应.	0
69	邝远平会长带队到十堰市竹溪县考察对接项目合作	https://www.52hrtt.com/sln/n/w/info/F1749120196246	随后来到了竹溪智算中心“国芯一号”项目基地，竹溪县副县长严小辉介绍了基地基本情况，及未来发展规划。大家对竹溪县在人工智能数字经济产业领域已做的 ...	0
70	2024年10月全国43个智算中心项目最新进展	https://www.jiechezdh.com/corporatenews/935.html	竹溪“国芯一号”智算中心正式上线秦巴算力峰会暨“国芯一号”智算中心上线发布会举行。此项目由科大讯飞携手华为助力建设，总体设计200P算力，一期建设50P，并利用区域智 ...	0
71	校领导带队赴竹溪县深化校地合作	https://www.hjnu.edu.cn/info/1046/9857.htm	签约仪式前，付永昌一行在竹溪县领导的陪同下，深入国芯一号智算中心、竹溪县外国语学校走访调研、访企拓岗，并与竹溪县教育局、竹溪县第二高级中学 ...	0
72	财经_华南财经网	https://www.huanancj.com/m/list.php?tid=179&TotalResult=2353&PageNo=58	“国芯一号”上线一周年交出亮眼答卷，助竹溪县域数字经济再上新阶. 时间：2025-10-20 22:56:41 栏目：国内财经 · 首页 上一页 下一页 末页 共236页2353条. 电脑版 - 免责 ...	0
73	极海半导体（深圳）有限公司	https://www.qcc.com/firm/d3cf818de3aa5630281b7b59a7c8c79f.html	深圳国芯一号半导体有限公司. 3. 深圳市领芯半导体有限公司. 4. 富芯半导体（深圳）有限公司. 5. 深圳市容疆半导体有限公司. 6. 深圳云极先芯半导体有限公司. 7. 晶通半导体 ...	0
74	动态丨安康市白河县发改局赴湖北省竹溪等县开展“十五 ...	https://c.m.163.com/news/a/KDK5K8RV0514D43D.html	考察组实地调研了竹溪县低空经济产业园(仁合智航无人机生产)和数字经济产业园(“国芯一号”智算中心)、竹山县中国绿松石交易中心等项目，深入了解竹溪县 ...	0
75	“讯飞星火”将再升级，又一行业大模型落地	https://news.qq.com/rain/a/20241022A07BT500	“国芯一号”一期建设50P人工智能算力底座，将在数字经济发展、区域协同、绿色可持续和技术创新等方面为竹溪注入发展动能。通过提供先进的算法、强大的算力和 ...	0
76	财经/ 财经要闻_大众财经网	https://www.dzcjw.com/m/list.php?tid=6&TotalResult=3795&PageNo=135	“国芯一号”上线一周年交出亮眼答卷，助竹溪县域数字经济再上新阶. 时间：2025-10-21 13:43:05 栏目：财经要闻 · 2025度小满西安马拉松男子组冠军王红伟点赞赛事服务完善.	0
77	投资者提问：竹溪县竞逐数字经济新赛道	https://www.163.com/dy/article/KDEVNVNJ05568W0A.html	... 国芯一号”生态合作伙伴大会。考拉悠然计划在“国芯一号”智算中心投入150P算力进行大模型开发，进一步完善“基础设施-技术研发-场景应用”产业链条。此次 ...	0
78	人物访谈_中国IDC圈	https://cio.idcquan.com/talk/2.shtml	4竹溪“国芯一号”一周年：算力为基，县域经; 5从概念愿景到工程就绪：维谛携手NVIDIA推进; 6城域算力中心互联时延<1毫秒工信部启动城; 7探前沿聚合力，产业平台助力电工 ...	0
79	智创未来提质向新| 湖北全力构筑中部崛起“数字引擎”	https://m.10100.com/article/30246798	... 国芯一号”智算中心均已投运，孵化文旅、农业、政务、安全等行业大模型，服务当地产业智能化转型与升级。 以点带面，全业融合。从医疗领域AI诊断准确率超96%，到东风 ...	0
80	谷歌宣布在泰国和马来西亚投资30亿美元云计算和数据中心	https://www.dtdata.cn/index.php?c=show&id=2547	竹溪“国芯一号”智算中心正式上线. 下一篇：12.7亿！郑州人工智能计算中心（二期）项目算力集群部分建设、维护、运营一体化招标计划发布. 相关推荐. 发表 ...	0
81	省媒聚焦：十堰茶产业冲刺百亿元年产值	http://m.10yan.com/m/showArt.html?contentid=925225	近年来，竹溪依托5G技术、国芯一号智算中心，打造智慧茶园，配备环境监测、智能灌溉等系统，实现茶叶生长质量标准化、茶园管理数字化。 数智加持，茶 ...	0
82	问董秘	https://finance.sina.cn/other/relnews/dongmiqa_list.d.html?oid=20&vt=4&wm=4007&market=sz&code=300608	... 国芯一号”生态合作伙伴大会。考拉悠然计划在“国芯一号”智算中心投入150P算力进行大模型开发，进一步完善“基础设施-技术研发-场景应用”产业链条。此次签约是公司践行“多 ...	0
83	华为海思图灵开发部	https://www.douyin.com/search/%E5%8D%8E%E4%B8%BA%E6%B5%B7%E6%80%9D%E5%9B%BE%E7%81%B5%E5%BC%80%E5%8F%91%E9%83%A8	7小时前. 数智直通车| 华为发力“国芯一号”一周年：县城“算力革命”交出满意答卷！（视频来源：@AI真探阿泽）#数智直通车#数智世界一触即达#华为#国芯一号#华为超节点.	0
84	Arm 计算- 极术社区- 连接开发者与智能计算生态	https://aijishu.com/channel/server	竹溪“国芯一号”一周年：算力为基，县域经济“乘势跃升”启新程. 地处中国版图心脏位置的竹溪县，携手华为与科大讯飞建设的“国芯一号”智算中心已于2024年10月正式 ...	0
85	动态丨安康市白河县发改局赴湖北省竹溪等县开展“ ...	https://www.163.com/dy/article/KDK5K8RV0514D43D.html	考察组实地调研了竹溪县低空经济产业园(仁合智航无人机生产)和数字经济产业园(“国芯一号”智算中心)、竹山县中国绿松石交易中心等项目，深入了解竹溪县 ...	0
86	行业资讯动态频道_软盟科技有限公司	https://group.softunis.com/news	一、引言在当今数字化时代，算力如同数字经济时代的核心引擎，推动着从科学研究到日常生活的各个领域的快速发展。“国芯一号”智算中心一期50P国产化算力底座正式投入运营，这一 ...	0
87	益企研究院	https://blog.csdn.net/xiaomishu001	竹溪“国芯一号”一周年：算力为基，县域经济“乘势跃升”启新程. 阅读量：292 2025-10-20 14:33:12. AICC2025 智算中心与算力服务论坛顺利举办. 阅读量：578 2025-10-11 16 ...	0
88	财经> 财经要闻> 列表 - 大众财经网	https://www.dzcjw.com/m/list.php?tid=6&TotalResult=2341&PageNo=129	“国芯一号”上线一周年交出亮眼答卷，助竹溪县域数字经济再上新阶. 时间：2025-10-21 13:43:05 栏目：财经要闻 · 2025度小满西安马拉松男子组冠军王红伟点赞赛事服务完善.	0
89	思特奇：参股公司考拉悠然参与竹溪数字经济招商签约	https://finance.sina.com.cn/stock/relnews/dongmiqa/2025-11-03/doc-infwcefr2596547.shtml?froms=ggmp	... 国芯一号”生态合作伙伴大会。考拉悠然计划在“国芯一号”智算中心投入150P算力进行大模型开发，进一步完善“基础设施-技术研发-场景应用”产业链条。此次 ...	0
90	6个月，155个大模型大单中标！附详细名单 - 富途资讯	https://news.futunn.com/post/58904389	... 国芯一号”智算中心，开发适用于竹溪县政务场景的人工智能大模型；上海数产是上海张江集团全资控股的国有独资企业；赢科天地的定位是为高校信息化建设 ...	0
91	财经/ 国内财经_华南财经网	https://huanancj.com/m/list.php?tid=183&TotalResult=1734&PageNo=42	“国芯一号”上线一周年交出亮眼答卷，助竹溪县域数字经济再上新阶. 时间：2025-10-20 22:56:41 栏目：国内财经 · 首页 上一页 下一页 末页 共174页1734条. 电脑版 - 免责 ...	0
92	湖北省公共资源交易云平台网站	https://www.hbbidcloud.cn/zhuxi/	... 国芯一号）监理服务项目报建公告(项目编号HBZH-202411QG-015) 2024-11-04; 【竹溪县中心】竹溪县通用航空机场建设项目可行性研究至初步设计编制服务项目项目报建公告 ...	0
93	国芯通科技张慧天涯	https://www.douyin.com/zhuanti/7186210827513661475	“国芯一号”为啥落户大山深处的十堰竹溪. 1.1W. 00:54 · “国芯一号”为啥落户大山深处的十堰竹溪？#十堰#竹溪#湖北#华正说 · @ 华正说 · 解放北路改造工程通车，坝子街到二环北 ...	0
94	湖北省公共资源交易云平台网站	https://bidcloud.llb.chutianyun.gov.cn/zhuxi/jyxx/004002/004002006/about.html	... 国芯一号）监理服务竹溪县数字经济产业园一期（竹溪县国芯一号）监理服务(HBZH-202411QG-015001001)招标公告[文件获取已截止]. 2024-11-05. 【竹溪县中心】竹溪蜂产业 ...	0
95	财经/ 国内财经_华南财经网	https://huanancj.com/m/list.php?tid=183&TotalResult=1836&PageNo=42	“国芯一号”上线一周年交出亮眼答卷，助竹溪县域数字经济再上新阶. 时间：2025-10-20 22:56:41 栏目：国内财经 · 首页 上一页 下一页 末页 共184页1836条. 电脑版 - 免责 ...	0
96	美国发出通缉令，逮捕中国芯片科学家陈正坤，如今怎么样了？	https://www.sohu.com/a/808480529_120525211	晋华公司在他的带领下，成功研发出“国芯一号”DRAM芯片，并实现大规模生产，为中国芯片产业注入了新的活力。 展开剩余58 %. 然而，随着晋华公司在芯片 ...	0
97	6个月，155个大模型大单中标！附详细名单	https://view.inews.qq.com/a/20250708A08DAC00	... 国芯一号”智算中心，开发适用于竹溪县政务场景的人工智能大模型；上海数产是上海张江集团全资控股的国有独资企业；赢科天地的定位是为高校信息化建设 ...	0
98	填补行业空白，科大讯飞助推“智算运维标准化”建立	https://finance.sina.com.cn/roll/2024-12-25/doc-ineasrzi0549635.shtml	... 国芯一号”注入新动能。全栈自主创新算力底座，为竹溪政务大模型、农业大模型等提供了算力“温床”，助力政务、农业、文旅研学等领域创新发展，繁荣当地 ...	0
99	推荐浙商银行深圳分行精彩亮相第十九届深圳 - 财经_华南财经网	https://www.huanancj.com/m/list.php?tid=179&TotalResult=2129&PageNo=58	“国芯一号”上线一周年交出亮眼答卷，助竹溪县域数字经济再上新阶. 时间：2025-10-20 22:56:41 栏目：国内财经 · 首页 上一页 下一页 末页 共213页2129条. 电脑版 - 免责 ...	0
100	数字经济	https://news.softunis.com/digital-economy	从湖北竹溪“国芯一号”算力生态圈的崛起，到阿里国际站AI助手重塑跨境贸易；从腾讯3D世界模型开源赋能工业仿真，到小鹏人形机器人“灵驹”量产降价……政策、技术、场景三重 ...	0
101	左手算力，右手大模型，湖北竹溪向着AI产业“换道超车”	https://www.sohu.com/a/819548324_615309	10月15日，竹溪“国芯一号”智算中心上线发布，竹溪正聚力以智算中心+特色行业大模型，推动城市AI产业快速发展。 “国芯一号”上线. 竹溪集齐AI产业“拼图 ...	0
102	“国芯一号”智算中心正式上线，科大讯飞与竹溪共筑算力未来	https://news.qq.com/rain/a/20241015A08G8900	“国芯一号”由科大讯飞携手华为助力建设，总体规划200P算力，一期建设50P，并利用区域智算中心底层算力及算法的资源训练、推理场景模型，助力竹溪建设以智算 ...	0
174	国芯科技芯片在动力底盘领域的突破与产品方案 | 「驶向未来:预约下一个十五•五驰骋世界」活动	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BamgBU5NNY0mEYkFP8aUe2FqXa8Fplpd9pMD6FSCBeHub5yHwkSAeyX9A5vslkWPnv0O0GO-ksD-9b5o7wGwH1H5PsFrq_QirnjvcOHTM-szd4t-1KFEQbEd718Xjqo5tsLPnhnzzny9C5Zkjv5tC73kn8yFmBG46J5qBWgzUE0uJr8_veOAWjEq7mJtY2slh-llEqWCaPy2FW6cwuUnkdA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BE94D1771D4CCA606725FF84747099619157EB6929115B		1
175	重磅签约丨航天壹进制成为北联国芯首批项目合作伙伴,携手共筑江苏鲲鹏产业生态	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BweBKyaJ9W-6EYkFP8aUe2FqXa8Fplpd985MHQnAW4nKOIoGZsMN81_moUqx9gw_eL4hUPzjbGoPTv5zNb8hhx0_Z-8g9znPIYQ1q91n40tF5lO5Yc175VWvLyOnEzqZQ1o1A3OpYTvysaQuDFNqXzrnrI8Rmz0YeJc53gooVPdBHWSOGoX20hD8Fz3Kn0JFx3-p5KA_A4tqTJmCU1UgHwQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BEA2C21B7020A00C0D4895E93161440CB7EA706929115D		1
176	老牌国产芯片公司国芯为AI再出发!获国投创合+创新工场1.5亿元融资	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BweBKyaJ9W-6EYkFP8aUe2FqXa8Fplpd9XSYwOOPmQ-qnuKL0w44I_bN3lkEFhOYjA1lLVSBBuZQOhDv7YnKoBYzXN6QDnTKwEADsg-Ph-SwWg-UOnHrK4QksscB6bvD_z1GEwtuj2ayzL6mYMGDihJ9tZh17NeXvU04sbbk1cu2P2qQf1KO59nBLsXeP2hLCMI3Lx2A_yKl535pjGOOjYg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BEA2C21B7020A00C0D4895E93161440CB7EA706929115D		1
177	振兴国芯,振奋人心!华为,我服你	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BweBKyaJ9W-6EYkFP8aUe2FqXa8Fplpd9iBmv6ECo6DpdsA-Oa9XkQ8h4ThxJAewAlnRBoUd2FWY-dbfBPSu_bCeo7uWvgk0KF5f0VV6CAWWl55UtbhO03RUsClt02N8nb2vfaYXYIrBFIM6vsrWQ4_P7PTJSA5Gg1eGn33CVE7PFqKuWtEiAv_bLVCpCrIxDWJLYT97NYm5Ae0f8bRARvQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BEA2C21B7020A00C0D4895E93161440CB7EA706929115D		1
178	今夏我最红 | 国芯梦:久经“沙场”的霸屏女神	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BweBKyaJ9W-6EYkFP8aUe2FqXa8Fplpd9KyhfEftFwpbsbYrnsmuQHR-ui_-ofmhSWneekw0wWDmwkRnR802uaUAF1QdpfrI0t5cavMO7LGOxookiJcW8rfQS_4yfz6FR98Lzeak0NKcVfhHFaGJDcNVAJHnlHRCmwIJP_dp0Pwj7HVQoIhz6LjnL6YXEBwnVf1gvHqV_GgYYJSSFPgfogQ..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BEA2C21B7020A00C0D4895E93161440CB7EA706929115D		1
179	重磅签约丨航天壹进制成为北联国芯首批项目合作伙伴,携手共筑江苏鲲鹏产业生态	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BweBKyaJ9W-6EYkFP8aUe2FqXa8Fplpd9fe3-oD2Au_RAFlDnI9fu7wK8cf5Qe4xGZuaJzujiYkkXfH8VEb-zv7sLflk7mbzg0iVKovGPh3bXQWZS28XzlOxVlvSnOwuRfpgqBVkFuw75vi5VcIhIuhpIgVsGN6UcR-ymFZVF8U8iKYWmp70jxigN-BmjsnsxprRH8EiIHCl535pjGOOjYg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BEA2C21B7020A00C0D4895E93161440CB7EA706929115D		1
180	美国多家科技公司大裁员,寒意传递到硅谷每一个人;2022胡润百富榜发布,张一鸣位列第二;歌尔股份丢掉苹果耳机订单丨雷峰早报	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BweBKyaJ9W-6EYkFP8aUe2FqXa8Fplpd9cTQexKFp4sDV1BI1Hml8zzTqLrTgPVLGDEoIKvojNnsGojLBlI5l-XF_PDYDrsL99aRX-QKJYax8TcprnV1lzZUCOq8JF4X3Ae5OMCxjpDg_ZtbQp897oe3ISgVc_LE6ycBGlqUlCqQtwVnbSthzeU0HyH1aGV2XYV2urdapi6XRtmyIGw2VAg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BEA2C21B7020A00C0D4895E93161440CB7EA706929115D		1
181	中国一出手 美股就出现89年来大萧条 而这只是刚刚开始 | 檀财经	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BweBKyaJ9W-6EYkFP8aUe2FqXa8Fplpd9WvefrX8zLqQQ1EoKSA1n0bEHcFuzlTpKr6FbzhkNszY0Mgx2tyTSVCls8Ihw45axwCT_VNTsG0byMlTkgnkafpa1rpdl_NE8sQq9-xhxgiDm3x1MOsj0KVy9z5W1bcJQmPnfQJwWBYX2i9tl7SanNg8AqsK4pgHFf9_kv5AYfHNe0WC6Sbi7DA..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BEA2C21B7020A00C0D4895E93161440CB7EA706929115D		1
182	这家公司就像一辆公交车 控股股东轮流上 没有留下一根鸡毛 | 上市公司扫雷系列	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BweBKyaJ9W-6EYkFP8aUe2FqXa8Fplpd9WvefrX8zLqQQ1EoKSA1n0bEHcFuzlTpKr6FbzhkNszY0Mgx2tyTSVHSfviTbqPslKjTuct6yDJrOGWRzL-dpgwzkbH3b0v0USwzlXBhD0Ppevbv4HpELZ7YRFPsJCDMjnVXr0Xyxl6MsKH8KWUAnC9UNn4D9FaEKOyCPwak1lBQCn9lOoZLP2Q..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BEA2C21B7020A00C0D4895E93161440CB7EA706929115D		1
183	成都适合遛娃的9个特色室内景点!大部分免费!	https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgSxsELkr7Rg_BweBKyaJ9W-6EYkFP8aUe2FqXa8Fplpd9JQkDnpZc2tS5oC6BBDdIlEA9W_AFD_IPwwuYIT8k5MZAdl6aAoIoDSxtVmARsdujruPyskG_T2yxAg3geLrH98ksK5f37qL2dlQo3lZ7mr1faG22SDMEs9xi8bCC6KHfkgpDPW2IMY04ujNzOi3ILmoKTLQyc7X-c_pUx2EGJyrvzHZXxeLdyg..&type=2&query=%E5%9B%BD%E8%8A%AF%E4%B8%80%E5%8F%B7&token=84BEA2C21B7020A00C0D4895E93161440CB7EA706929115D		1
\.


--
-- Data for Name: search_result_label; Type: TABLE DATA; Schema: public; Owner: search
--

COPY public.search_result_label (search_result_id, label_id) FROM stdin;
102	1
102	2
\.


--
-- Name: label_id_seq; Type: SEQUENCE SET; Schema: public; Owner: search
--

SELECT pg_catalog.setval('public.label_id_seq', 2, true);


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: search
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- Name: search_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: search
--

SELECT pg_catalog.setval('public.search_result_id_seq', 183, true);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: search
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: label label_pkey; Type: CONSTRAINT; Schema: public; Owner: search
--

ALTER TABLE ONLY public.label
    ADD CONSTRAINT label_pkey PRIMARY KEY (id);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: search
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: search_result_label search_result_label_pkey; Type: CONSTRAINT; Schema: public; Owner: search
--

ALTER TABLE ONLY public.search_result_label
    ADD CONSTRAINT search_result_label_pkey PRIMARY KEY (search_result_id, label_id);


--
-- Name: search_result search_result_pkey; Type: CONSTRAINT; Schema: public; Owner: search
--

ALTER TABLE ONLY public.search_result
    ADD CONSTRAINT search_result_pkey PRIMARY KEY (id);


--
-- Name: idx_75ea56e016ba31db; Type: INDEX; Schema: public; Owner: search
--

CREATE INDEX idx_75ea56e016ba31db ON public.messenger_messages USING btree (delivered_at);


--
-- Name: idx_75ea56e0e3bd61ce; Type: INDEX; Schema: public; Owner: search
--

CREATE INDEX idx_75ea56e0e3bd61ce ON public.messenger_messages USING btree (available_at);


--
-- Name: idx_75ea56e0fb7336f0; Type: INDEX; Schema: public; Owner: search
--

CREATE INDEX idx_75ea56e0fb7336f0 ON public.messenger_messages USING btree (queue_name);


--
-- Name: idx_889fd0ba33b92f39; Type: INDEX; Schema: public; Owner: search
--

CREATE INDEX idx_889fd0ba33b92f39 ON public.search_result_label USING btree (label_id);


--
-- Name: idx_889fd0babcbca6eb; Type: INDEX; Schema: public; Owner: search
--

CREATE INDEX idx_889fd0babcbca6eb ON public.search_result_label USING btree (search_result_id);


--
-- Name: search_result_label fk_889fd0ba33b92f39; Type: FK CONSTRAINT; Schema: public; Owner: search
--

ALTER TABLE ONLY public.search_result_label
    ADD CONSTRAINT fk_889fd0ba33b92f39 FOREIGN KEY (label_id) REFERENCES public.label(id) ON DELETE CASCADE;


--
-- Name: search_result_label fk_889fd0babcbca6eb; Type: FK CONSTRAINT; Schema: public; Owner: search
--

ALTER TABLE ONLY public.search_result_label
    ADD CONSTRAINT fk_889fd0babcbca6eb FOREIGN KEY (search_result_id) REFERENCES public.search_result(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

